from datetime import date, datetime, timedelta
from dateutil.relativedelta import relativedelta

from openerp.addons.pentaho_reports.java_oe import *

FTYPE_TIMEDELTA = 'tdel'
FUNCTION_TYPES = OPENERP_DATA_TYPES + [(FTYPE_TIMEDELTA, 'Time Delta')]

FORMULAE = {'now': {'type': TYPE_TIME,
                    'parameters': [],
                    'call': 'self.localise(cr, uid, datetime.now(), context=context)',
                    },
            'today': {'type': TYPE_DATE,
                      'parameters': [],
                      'call': 'self.localise(cr, uid, datetime.today(), context=context).date()',
                      },
            'start_of_month': {'type': TYPE_DATE,
                               'parameters': [],
                               'call': 'self.localise(cr, uid, datetime.today(), context=context).date() + relativedelta(day=1)',
                               },
            'start_of_year': {'type': TYPE_DATE,
                              'parameters': [],
                              'call': 'self.localise(cr, uid, datetime.today(), context=context).date() + relativedelta(day=1, month=1)',
                              },
            'next_sunday': {'type': TYPE_DATE,
                            'parameters': [],
                            'call': 'self.localise(cr, uid, datetime.today(), context=context).date() + relativedelta(weekday=6)',
                            },
            'next_monday': {'type': TYPE_DATE,
                            'parameters': [],
                            'call': 'self.localise(cr, uid, datetime.today(), context=context).date() + relativedelta(weekday=0)',
                            },
            'next_friday': {'type': TYPE_DATE,
                            'parameters': [],
                            'call': 'self.localise(cr, uid, datetime.today(), context=context).date() + relativedelta(weekday=5)',
                            },

            'years': {'type': FTYPE_TIMEDELTA,
                      'parameters': [('years', (TYPE_INTEGER, TYPE_NUMBER)),
                                     ],
                      'call': 'relativedelta(%1)',
                      },
            'months': {'type': FTYPE_TIMEDELTA,
                       'parameters': [('months', (TYPE_INTEGER, TYPE_NUMBER)),
                                      ],
                       'call': 'relativedelta(%1)',
                       },
            'weeks': {'type': FTYPE_TIMEDELTA,
                      'parameters': [('weeks', (TYPE_INTEGER, TYPE_NUMBER)),
                                     ],
                      'call': 'relativedelta(%1)',
                      },
            'hours': {'type': FTYPE_TIMEDELTA,
                      'parameters': [('hours', (TYPE_INTEGER, TYPE_NUMBER)),
                                     ],
                      'call': 'relativedelta(%1)',
                      },
            'minutes': {'type': FTYPE_TIMEDELTA,
                        'parameters': [('minutes', (TYPE_INTEGER, TYPE_NUMBER)),
                                       ],
                        'call': 'relativedelta(%1)',
                        },
            'seconds': {'type': FTYPE_TIMEDELTA,
                        'parameters': [('secondes', (TYPE_INTEGER, TYPE_NUMBER)),
                                       ],
                        'call': 'relativedelta(%1)',
                        },
            }

